name: Build & Deploy to Netlify

# https://qiita.com/nwtgck/items/e9a355c2ccb03d8e8eb0

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    # - name: Output names
    #   run: |
    #     GITHUB_TOKEN=""
    #     if [ "${{ github.event_name }}" = "pull_request" ];then
    #       GITHUB_TOKEN="${{ github.token }}"
    #     fi
    #     echo "##[set-output name=notif-token]$GITHUB_TOKEN"
    #     echo "##[set-output name=yarn-cache]$(yarn cache dir)"

    - name: Output current branch name
      uses: satackey/action-js-inline@release-master
      id: names
      with:
        required-packages: actions-exec-wrapper
        event: ${{ github.event_name }}
        script: |
          const core = require('@actions/core')
          const exec = require('actions-exec-wrapper')

          const eventName = core.getInput('event')
          const token = eventName === 'pull_request' ? process.env.GITHUB_TOKEN : ''
          core.setOutput('notif-token', token)

          return exec.exec('yarn cache dir').then(({ stdoutStr }) => {
            core.setOutput('yarn-cache', stdoutStr)
          }) 

    - name: Restore yarn cache
      uses: actions/cache@v1
      with:
        path: ${{ steps.names.outputs.yarn-cache }}
        key: ${{ runner.OS }}-yarn-${{ hashFiles('package.json') }}-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.OS }}-yarn-${{ hashFiles('package.json') }}-
          ${{ runner.OS }}-yarn-

    - name: Restore Gatsby build cache
      uses: actions/cache@v1
      with:
        path: .cache
        key: ${{ runner.OS }}-gatsby-${{ hashFiles('**.md') }}-${{ hashFiles('package.json') }}-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.OS }}-gatsby-${{ hashFiles('**.md') }}-${{ hashFiles('package.json') }}-
          ${{ runner.OS }}-gatsby-${{ hashFiles('**.md') }}-
          ${{ runner.OS }}-gatsby-

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    # - name: Run test
    #   run: yarn test

    - name: Build
      run: yarn build

    - name: Deploy
      uses: nwtgck/actions-netlify@v1.0
      if: github.event_name == 'pull_request' || contains(github.ref, 'master')
      with:
        publish-dir: public
        production-branch: master
        github-token: ${{ steps.names.outputs.notiftoken }}
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
