name: Build & Deploy to Netlify

# https://qiita.com/nwtgck/items/e9a355c2ccb03d8e8eb0

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    # - name: Run test
    #   run: yarn test

    - name: Build
      run: yarn build

    - name: Deploy
      uses: nwtgck/actions-netlify@v1.0
      with:
        publish-dir: public
        production-branch: master
        github-token: ${{ github.token }}
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
